package com.jswiente.phd.prototype.domain;

// Generated 06.03.2012 20:55:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "billdb", uniqueConstraints = @UniqueConstraint(columnNames = "AccountNum"))
public class Account implements Record, java.io.Serializable {

	private long accountId;
	private Customer customer;
	private long accountNum;
	private Long billCylce;
	private Date lastBillDate;
	private Date nextBillDate;
	private Set<Costedevent> costedevents = new HashSet<Costedevent>(0);

	public Account() {
	}

	public Account(long accountId, long accountNum) {
		this.accountId = accountId;
		this.accountNum = accountNum;
	}

	public Account(long accountId, Customer customer, long accountNum,
			Long billCylce, Date lastBillDate, Date nextBillDate,
			Set<Costedevent> costedevents) {
		this.accountId = accountId;
		this.customer = customer;
		this.accountNum = accountNum;
		this.billCylce = billCylce;
		this.lastBillDate = lastBillDate;
		this.nextBillDate = nextBillDate;
		this.costedevents = costedevents;
	}

	@Id
	@Column(name = "AccountId", unique = true, nullable = false)
	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerId")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "AccountNum", unique = true, nullable = false)
	public long getAccountNum() {
		return this.accountNum;
	}

	public void setAccountNum(long accountNum) {
		this.accountNum = accountNum;
	}

	@Column(name = "BillCylce")
	public Long getBillCylce() {
		return this.billCylce;
	}

	public void setBillCylce(Long billCylce) {
		this.billCylce = billCylce;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastBillDate", length = 19)
	public Date getLastBillDate() {
		return this.lastBillDate;
	}

	public void setLastBillDate(Date lastBillDate) {
		this.lastBillDate = lastBillDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NextBillDate", length = 19)
	public Date getNextBillDate() {
		return this.nextBillDate;
	}

	public void setNextBillDate(Date nextBillDate) {
		this.nextBillDate = nextBillDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Costedevent> getCostedevents() {
		return this.costedevents;
	}

	public void setCostedevents(Set<Costedevent> costedevents) {
		this.costedevents = costedevents;
	}

}
