package com.jswiente.phd.prototype.domain;

// Generated 03.03.2012 10:25:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Costedevent generated by hbm2java
 */
@Entity
@Table(name = "costedevent", schema = "billdb")
public class Costedevent implements java.io.Serializable {

	private static final long serialVersionUID = 4981105880133518104L;
	
	private long costedEventId;
	private Account account;
	private Long sequenceNum;
	private Date startDate;
	private Date endDate;
	private String callingParty;
	private String calledParty;
	private String callType;

	public Costedevent() {
	}

	public Costedevent(long costedEventId) {
		this.costedEventId = costedEventId;
	}

	public Costedevent(long costedEventId, Account account, Long sequenceNum,
			Date startDate, Date endDate, String callingParty,
			String calledParty, String callType) {
		this.costedEventId = costedEventId;
		this.account = account;
		this.sequenceNum = sequenceNum;
		this.startDate = startDate;
		this.endDate = endDate;
		this.callingParty = callingParty;
		this.calledParty = calledParty;
		this.callType = callType;
	}

	@Id
	@Column(name = "CostedEventId", unique = true, nullable = false)
	public long getCostedEventId() {
		return this.costedEventId;
	}

	public void setCostedEventId(long costedEventId) {
		this.costedEventId = costedEventId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccountId")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "SequenceNum")
	public Long getSequenceNum() {
		return this.sequenceNum;
	}

	public void setSequenceNum(Long sequenceNum) {
		this.sequenceNum = sequenceNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "CallingParty", length = 50)
	public String getCallingParty() {
		return this.callingParty;
	}

	public void setCallingParty(String callingParty) {
		this.callingParty = callingParty;
	}

	@Column(name = "CalledParty", length = 50)
	public String getCalledParty() {
		return this.calledParty;
	}

	public void setCalledParty(String calledParty) {
		this.calledParty = calledParty;
	}

	@Column(name = "CallType", length = 5)
	public String getCallType() {
		return this.callType;
	}

	public void setCallType(String callType) {
		this.callType = callType;
	}

}
