package com.jswiente.phd.prototype.domain;

// Generated 03.03.2012 10:25:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customerproducttariff generated by hbm2java
 */
@Entity
@Table(name = "customerproducttariff", schema = "billdb")
public class Customerproducttariff implements java.io.Serializable {

	private static final long serialVersionUID = -3159349669482697987L;
	
	private long customerProductTariffId;
	private Tariff tariff;
	private long customerId;
	private long productSeq;
	private Date startDate;
	private Date endDate;
	private Set<Customerproduct> customerproducts = new HashSet<Customerproduct>(
			0);

	public Customerproducttariff() {
	}

	public Customerproducttariff(long customerProductTariffId, long customerId,
			long productSeq, Date startDate) {
		this.customerProductTariffId = customerProductTariffId;
		this.customerId = customerId;
		this.productSeq = productSeq;
		this.startDate = startDate;
	}

	public Customerproducttariff(long customerProductTariffId, Tariff tariff,
			long customerId, long productSeq, Date startDate, Date endDate,
			Set<Customerproduct> customerproducts) {
		this.customerProductTariffId = customerProductTariffId;
		this.tariff = tariff;
		this.customerId = customerId;
		this.productSeq = productSeq;
		this.startDate = startDate;
		this.endDate = endDate;
		this.customerproducts = customerproducts;
	}

	@Id
	@Column(name = "CustomerProductTariffId", unique = true, nullable = false)
	public long getCustomerProductTariffId() {
		return this.customerProductTariffId;
	}

	public void setCustomerProductTariffId(long customerProductTariffId) {
		this.customerProductTariffId = customerProductTariffId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TariffId")
	public Tariff getTariff() {
		return this.tariff;
	}

	public void setTariff(Tariff tariff) {
		this.tariff = tariff;
	}

	@Column(name = "CustomerId", nullable = false)
	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "ProductSeq", nullable = false)
	public long getProductSeq() {
		return this.productSeq;
	}

	public void setProductSeq(long productSeq) {
		this.productSeq = productSeq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerproducttariff")
	public Set<Customerproduct> getCustomerproducts() {
		return this.customerproducts;
	}

	public void setCustomerproducts(Set<Customerproduct> customerproducts) {
		this.customerproducts = customerproducts;
	}

}
