package com.jswiente.phd.prototype.domain;

// Generated 03.03.2012 10:25:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", schema = "billdb")
public class Customer implements java.io.Serializable {

	private static final long serialVersionUID = -2443027282900878936L;
	
	private long customerId;
	private String salutation;
	private String titel;
	private String name;
	private String surname;
	private Date birthday;
	private String street;
	private String zip;
	private String city;
	private String phone;
	private String mobile;
	private String fax;
	private String mail;
	private Set<Customerproduct> customerproducts = new HashSet<Customerproduct>(
			0);
	private Set<Account> accounts = new HashSet<Account>(0);

	public Customer() {
	}

	public Customer(long customerId) {
		this.customerId = customerId;
	}

	public Customer(long customerId, String salutation, String titel,
			String name, String surname, Date birthday, String street,
			String zip, String city, String phone, String mobile, String fax,
			String mail, Set<Customerproduct> customerproducts,
			Set<Account> accounts) {
		this.customerId = customerId;
		this.salutation = salutation;
		this.titel = titel;
		this.name = name;
		this.surname = surname;
		this.birthday = birthday;
		this.street = street;
		this.zip = zip;
		this.city = city;
		this.phone = phone;
		this.mobile = mobile;
		this.fax = fax;
		this.mail = mail;
		this.customerproducts = customerproducts;
		this.accounts = accounts;
	}

	@Id
	@Column(name = "CustomerId", unique = true, nullable = false)
	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "Salutation", length = 5)
	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	@Column(name = "Titel", length = 5)
	public String getTitel() {
		return this.titel;
	}

	public void setTitel(String titel) {
		this.titel = titel;
	}

	@Column(name = "Name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Surname", length = 50)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Birthday", length = 19)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "Street", length = 80)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "Zip", length = 15)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "City", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "Phone", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Mobile", length = 50)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "Fax", length = 50)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "Mail", length = 50)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Customerproduct> getCustomerproducts() {
		return this.customerproducts;
	}

	public void setCustomerproducts(Set<Customerproduct> customerproducts) {
		this.customerproducts = customerproducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
