package com.jswiente.phd.prototype.domain;

// Generated 06.03.2012 20:55:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customerproducttariff generated by hbm2java
 */
@Entity
@Table(name = "customerproducttariff", catalog = "billdb")
public class Customerproducttariff implements Record, java.io.Serializable {

	private long customerProductTariffId;
	private Tariff tariff;
	private Customerproduct customerproduct;
	private Date startDate;
	private Date endDate;

	public Customerproducttariff() {
	}

	public Customerproducttariff(long customerProductTariffId,
			Customerproduct customerproduct, Date startDate) {
		this.customerProductTariffId = customerProductTariffId;
		this.customerproduct = customerproduct;
		this.startDate = startDate;
	}

	public Customerproducttariff(long customerProductTariffId, Tariff tariff,
			Customerproduct customerproduct, Date startDate, Date endDate) {
		this.customerProductTariffId = customerProductTariffId;
		this.tariff = tariff;
		this.customerproduct = customerproduct;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@Column(name = "CustomerProductTariffId", unique = true, nullable = false)
	public long getCustomerProductTariffId() {
		return this.customerProductTariffId;
	}

	public void setCustomerProductTariffId(long customerProductTariffId) {
		this.customerProductTariffId = customerProductTariffId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TariffId")
	public Tariff getTariff() {
		return this.tariff;
	}

	public void setTariff(Tariff tariff) {
		this.tariff = tariff;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerProductId", nullable = false)
	public Customerproduct getCustomerproduct() {
		return this.customerproduct;
	}

	public void setCustomerproduct(Customerproduct customerproduct) {
		this.customerproduct = customerproduct;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
