package com.jswiente.phd.prototype.domain;

// Generated 03.03.2012 10:25:32 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eventsource generated by hbm2java
 */
@Entity
@Table(name = "eventsource", schema = "billdb")
public class Eventsource implements java.io.Serializable {

	private static final long serialVersionUID = 1690704542239299185L;
	
	private long eventSourceId;
	private Tariff tariff;
	private Customerproduct customerproduct;
	private String eventSource;
	private Date startDate;
	private String eventType;
	private long customerId;
	private long productSeq;

	public Eventsource() {
	}

	public Eventsource(long eventSourceId, String eventSource, Date startDate,
			String eventType, long customerId, long productSeq) {
		this.eventSourceId = eventSourceId;
		this.eventSource = eventSource;
		this.startDate = startDate;
		this.eventType = eventType;
		this.customerId = customerId;
		this.productSeq = productSeq;
	}

	public Eventsource(long eventSourceId, Tariff tariff,
			Customerproduct customerproduct, String eventSource,
			Date startDate, String eventType, long customerId, long productSeq) {
		this.eventSourceId = eventSourceId;
		this.tariff = tariff;
		this.customerproduct = customerproduct;
		this.eventSource = eventSource;
		this.startDate = startDate;
		this.eventType = eventType;
		this.customerId = customerId;
		this.productSeq = productSeq;
	}

	@Id
	@Column(name = "EventSourceId", unique = true, nullable = false)
	public long getEventSourceId() {
		return this.eventSourceId;
	}

	public void setEventSourceId(long eventSourceId) {
		this.eventSourceId = eventSourceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RatingTariffId")
	public Tariff getTariff() {
		return this.tariff;
	}

	public void setTariff(Tariff tariff) {
		this.tariff = tariff;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerProductId")
	public Customerproduct getCustomerproduct() {
		return this.customerproduct;
	}

	public void setCustomerproduct(Customerproduct customerproduct) {
		this.customerproduct = customerproduct;
	}

	@Column(name = "EventSource", nullable = false, length = 50)
	public String getEventSource() {
		return this.eventSource;
	}

	public void setEventSource(String eventSource) {
		this.eventSource = eventSource;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startDate", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "eventType", nullable = false, length = 5)
	public String getEventType() {
		return this.eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	@Column(name = "CustomerId", nullable = false)
	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "ProductSeq", nullable = false)
	public long getProductSeq() {
		return this.productSeq;
	}

	public void setProductSeq(long productSeq) {
		this.productSeq = productSeq;
	}

}
