package com.jswiente.phd.prototype.domain;

// Generated 06.03.2012 20:55:50 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "billdb")
public class Product implements Record, java.io.Serializable {

	private long productId;
	private String name;
	private Set<Customerproduct> customerproducts = new HashSet<Customerproduct>(
			0);

	public Product() {
	}

	public Product(long productId) {
		this.productId = productId;
	}

	public Product(long productId, String name,
			Set<Customerproduct> customerproducts) {
		this.productId = productId;
		this.name = name;
		this.customerproducts = customerproducts;
	}

	@Id
	@Column(name = "ProductId", unique = true, nullable = false)
	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	@Column(name = "Name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Customerproduct> getCustomerproducts() {
		return this.customerproducts;
	}

	public void setCustomerproducts(Set<Customerproduct> customerproducts) {
		this.customerproducts = customerproducts;
	}

	@Override
	public long getId() {
		return productId;
	}

}
