package com.jswiente.phd.prototype.domain;

// Generated 06.03.2012 20:55:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tariff generated by hbm2java
 */
@Entity
@Table(name = "tariff", catalog = "billdb")
public class Tariff implements Record, java.io.Serializable {

	private long tarifId;
	private Date startDate;
	private Date endDate;
	private BigDecimal monthlyCharges;
	private BigDecimal usageCharges;
	private Set<Customerproducttariff> customerproducttariffs = new HashSet<Customerproducttariff>(
			0);

	public Tariff() {
	}

	public Tariff(long tarifId) {
		this.tarifId = tarifId;
	}

	public Tariff(long tarifId, Date startDate, Date endDate,
			BigDecimal monthlyCharges, BigDecimal usageCharges,
			Set<Customerproducttariff> customerproducttariffs) {
		this.tarifId = tarifId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.monthlyCharges = monthlyCharges;
		this.usageCharges = usageCharges;
		this.customerproducttariffs = customerproducttariffs;
	}

	@Id
	@Column(name = "TarifId", unique = true, nullable = false)
	public long getTarifId() {
		return this.tarifId;
	}

	public void setTarifId(long tarifId) {
		this.tarifId = tarifId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "MonthlyCharges", precision = 8)
	public BigDecimal getMonthlyCharges() {
		return this.monthlyCharges;
	}

	public void setMonthlyCharges(BigDecimal monthlyCharges) {
		this.monthlyCharges = monthlyCharges;
	}

	@Column(name = "UsageCharges", precision = 8)
	public BigDecimal getUsageCharges() {
		return this.usageCharges;
	}

	public void setUsageCharges(BigDecimal usageCharges) {
		this.usageCharges = usageCharges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tariff")
	public Set<Customerproducttariff> getCustomerproducttariffs() {
		return this.customerproducttariffs;
	}

	public void setCustomerproducttariffs(
			Set<Customerproducttariff> customerproducttariffs) {
		this.customerproducttariffs = customerproducttariffs;
	}

	public long getId() {
		return tarifId;
	}

}
